### PR TITLE
Update Readme with FAQ & Remove broken links

### PR DESCRIPTION
**Pull request by deepakgrewal**
Update Readme 
- FAQ for moving faker.js
- Remove old broken links

### CODE REVIEW

**Comment by micalevisk** [comment]
what about replacing `faker` by `@withshepherd/faker`

**Review by zoellner — APPROVED** [review]

**Comment by mmahalwy** [comment]
@deepakgrewal thanks for adding this! Agreed with @micalevisk - I can follow up with a PR here unless you want to own it

**Comment by mmahalwy** [comment]
Actually, will merge this now and we can follow on

**Comment by micalevisk** [comment]
@mmahalwy go ahead :)

**Pull request merged**
